In [1]:
import pandas as pd
import psycopg2 as psy
from datetime import date

In [16]:
dados = pd.read_csv('//192.168.0.171/Informatica/  Renan/2023/laser/JOBLISTA.pdf erro .csv',sep=',')
dados

,"Job elements list - 15,87MM ATA 12000 SC 16/01/2023",Page 1 of 1,24/01/2023,Nestings\42\42239,Nome do CNC,:,4086,Chapa,:.1,CHAPA- 5/8 ANTONIOSI,...,"14,26 %",Dimensões da chapa,:.9,6.000 x 1.510,Peças,:.10,127,Peso,:.11,"1.123,71 kg"
0,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42239,Nome do CNC,:,4086,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"14,26 %",Dimensões da chapa,:,6.000 x 1.510,Peças,:,127,Peso,:,"1.123,71 kg"
1,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42239,Nome do CNC,:,4086,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"14,26 %",Dimensões da chapa,:,6.000 x 1.510,Peças,:,127,Peso,:,"1.123,71 kg"
2,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42239,Nome do CNC,:,4086,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"14,26 %",Dimensões da chapa,:,6.000 x 1.510,Peças,:,127,Peso,:,"1.123,71 kg"
3,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42239,Nome do CNC,:,4086,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"14,26 %",Dimensões da chapa,:,6.000 x 1.510,Peças,:,127,Peso,:,"1.123,71 kg"
4,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42239,Nome do CNC,:,4086,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"14,26 %",Dimensões da chapa,:,6.000 x 1.510,Peças,:,127,Peso,:,"1.123,71 kg"
5,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42239,Nome do CNC,:,4086,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"14,26 %",Dimensões da chapa,:,6.000 x 1.510,Peças,:,127,Peso,:,"1.123,71 kg"
6,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42239,Nome do CNC,:,4086,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"14,26 %",Dimensões da chapa,:,6.000 x 1.510,Peças,:,127,Peso,:,"1.123,71 kg"
7,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42239,Nome do CNC,:,4086,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"14,26 %",Dimensões da chapa,:,6.000 x 1.510,Peças,:,127,Peso,:,"1.123,71 kg"
8,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42239,Nome do CNC,:,4086,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"14,26 %",Dimensões da chapa,:,6.000 x 1.510,Peças,:,127,Peso,:,"1.123,71 kg"
9,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42239,Nome do CNC,:,4086,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"14,26 %",Dimensões da chapa,:,6.000 x 1.510,Peças,:,127,Peso,:,"1.123,71 kg"
10,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42239,Nome do CNC,:,4086,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"14,26 %",Dimensões da chapa,:,6.000 x 1.510,Peças,:,127,Peso,:,"1.123,71 kg"
11,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42239,Nome do CNC,:,4086,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"14,26 %",Dimensões da chapa,:,6.000 x 1.510,Peças,:,127,Peso,:,"1.123,71 kg"
12,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42239,Nome do CNC,:,4086,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"14,26 %",Dimensões da chapa,:,6.000 x 1.510,Peças,:,127,Peso,:,"1.123,71 kg"
13,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42239,Nome do CNC,:,4086,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"14,26 %",Dimensões da chapa,:,6.000 x 1.510,Peças,:,127,Peso,:,"1.123,71 kg"
14,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42239,Nome do CNC,:,4086,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"14,26 %",Dimensões da chapa,:,6.000 x 1.510,Peças,:,127,Peso,:,"1.123,71 kg"
15,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42239,Nome do CNC,:,4086,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"14,26 %",Dimensões da chapa,:,6.000 x 1.510,Peças,:,127,Peso,:,"1.123,71 kg"
16,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42239,Nome do CNC,:,4086,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"14,26 %",Dimensões da chapa,:,6.000 x 1.510,Peças,:,127,Peso,:,"1.123,71 kg"
17,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42239,Nome do CNC,:,4086,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"14,26 %",Dimensões da chapa,:,6.000 x 1.510,Peças,:,127,Peso,:,"1.123,71 kg"
18,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42239,Nome do CNC,:,4086,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"14,26 %",Dimensões da chapa,:,6.000 x 1.510,Peças,:,127,Peso,:,"1.123,71 kg"
19,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42241,Nome do CNC,:,4087,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"35,23 %",Dimensões da chapa,:,3.000 x 1.510,Peças,:,93,Peso,:,"561,86 kg"
20,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42241,Nome do CNC,:,4087,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"35,23 %",Dimensões da chapa,:,3.000 x 1.510,Peças,:,93,Peso,:,"561,86 kg"
21,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42241,Nome do CNC,:,4087,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"35,23 %",Dimensões da chapa,:,3.000 x 1.510,Peças,:,93,Peso,:,"561,86 kg"
22,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42241,Nome do CNC,:,4087,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"35,23 %",Dimensões da chapa,:,3.000 x 1.510,Peças,:,93,Peso,:,"561,86 kg"
23,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42241,Nome do CNC,:,4087,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"35,23 %",Dimensões da chapa,:,3.000 x 1.510,Peças,:,93,Peso,:,"561,86 kg"
24,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42241,Nome do CNC,:,4087,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"35,23 %",Dimensões da chapa,:,3.000 x 1.510,Peças,:,93,Peso,:,"561,86 kg"
25,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42241,Nome do CNC,:,4087,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"35,23 %",Dimensões da chapa,:,3.000 x 1.510,Peças,:,93,Peso,:,"561,86 kg"
26,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42241,Nome do CNC,:,4087,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"35,23 %",Dimensões da chapa,:,3.000 x 1.510,Peças,:,93,Peso,:,"561,86 kg"
27,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42241,Nome do CNC,:,4087,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"35,23 %",Dimensões da chapa,:,3.000 x 1.510,Peças,:,93,Peso,:,"561,86 kg"
28,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42241,Nome do CNC,:,4087,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"35,23 %",Dimensões da chapa,:,3.000 x 1.510,Peças,:,93,Peso,:,"561,86 kg"
29,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42241,Nome do CNC,:,4087,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"35,23 %",Dimensões da chapa,:,3.000 x 1.510,Peças,:,93,Peso,:,"561,86 kg"
30,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42241,Nome do CNC,:,4087,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"35,23 %",Dimensões da chapa,:,3.000 x 1.510,Peças,:,93,Peso,:,"561,86 kg"
31,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42241,Nome do CNC,:,4087,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"35,23 %",Dimensões da chapa,:,3.000 x 1.510,Peças,:,93,Peso,:,"561,86 kg"
32,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42241,Nome do CNC,:,4087,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"35,23 %",Dimensões da chapa,:,3.000 x 1.510,Peças,:,93,Peso,:,"561,86 kg"
33,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42241,Nome do CNC,:,4087,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"35,23 %",Dimensões da chapa,:,3.000 x 1.510,Peças,:,93,Peso,:,"561,86 kg"
34,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42241,Nome do CNC,:,4087,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"35,23 %",Dimensões da chapa,:,3.000 x 1.510,Peças,:,93,Peso,:,"561,86 kg"
35,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42241,Nome do CNC,:,4087,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"35,23 %",Dimensões da chapa,:,3.000 x 1.510,Peças,:,93,Peso,:,"561,86 kg"
36,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42241,Nome do CNC,:,4087,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"35,23 %",Dimensões da chapa,:,3.000 x 1.510,Peças,:,93,Peso,:,"561,86 kg"
37,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42241,Nome do CNC,:,4087,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"35,23 %",Dimensões da chapa,:,3.000 x 1.510,Peças,:,93,Peso,:,"561,86 kg"
38,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42241,Nome do CNC,:,4087,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"35,23 %",Dimensões da chapa,:,3.000 x 1.510,Peças,:,93,Peso,:,"561,86 kg"
39,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42241,Nome do CNC,:,4087,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"35,23 %",Dimensões da chapa,:,3.000 x 1.510,Peças,:,93,Peso,:,"561,86 kg"
40,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42241,Nome do CNC,:,4087,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"35,23 %",Dimensões da chapa,:,3.000 x 1.510,Peças,:,93,Peso,:,"561,86 kg"
41,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42241,Nome do CNC,:,4087,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"35,23 %",Dimensões da chapa,:,3.000 x 1.510,Peças,:,93,Peso,:,"561,86 kg"
42,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42241,Nome do CNC,:,4087,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"35,23 %",Dimensões da chapa,:,3.000 x 1.510,Peças,:,93,Peso,:,"561,86 kg"
43,"Job elements list - 15,87MM ATA 12000 SC 16/01...",Page 1 of 1,24/01/2023,Nestings\42\42241,Nome do CNC,:,4087,Chapa,:,CHAPA- 5/8 ANTONIOSI,...,"35,23 %",Dimensões da chapa,:,3.000 x 1.510,Peças,:,93,Peso,:,"561,86 kg"

In [14]:
dados = pd.read_csv('//192.168.0.171/Informatica/  Renan/2023/laser/erro.csv',sep=',')
dados.to_csv('teste.csv',sep=';')

In [17]:
column_name = []
for i in range(40): 
    column_name.append(i+1)

In [18]:
df = pd.read_csv('//192.168.0.171/Informatica/  Renan/2023/laser/JOBLISTA.pdf erro .csv',sep=',',names=column_name,encoding='utf8')

In [19]:
#dados = df[[1,5,7,17,19,23,25,26,28,29,31,38,40]]

dados = df[[1,7,19,25,28,31,40]]

In [20]:
rename_list = ['Nome_Programa','CNC','Qtd','Tempo_corte','Espessura','Desperdicio','Peso']

In [21]:
dados.head()

,1,7,19,25,28,31,40
0,"Job elements list - 15,87MM ATA 12000 SC 16/01...",4086,1,02:50:56,"15,80 mm","14,26 %","1.123,71 kg"
1,"Job elements list - 15,87MM ATA 12000 SC 16/01...",4086,1,02:50:56,"15,80 mm","14,26 %","1.123,71 kg"
2,"Job elements list - 15,87MM ATA 12000 SC 16/01...",4086,1,02:50:56,"15,80 mm","14,26 %","1.123,71 kg"
3,"Job elements list - 15,87MM ATA 12000 SC 16/01...",4086,1,02:50:56,"15,80 mm","14,26 %","1.123,71 kg"
4,"Job elements list - 15,87MM ATA 12000 SC 16/01...",4086,1,02:50:56,"15,80 mm","14,26 %","1.123,71 kg"

In [36]:
dados.columns = rename_list

In [40]:
dados = dados.drop_duplicates(keep='first',subset='CNC')

In [25]:
dados.head()

,1,7,19,25,28,31,40
0,"Job elements list - 15,87MM ATA 12000 SC 16/01...",4086,1,02:50:56,"15,80 mm","14,26 %","1.123,71 kg"
1,"Job elements list - 15,87MM ATA 12000 SC 16/01...",4086,1,02:50:56,"15,80 mm","14,26 %","1.123,71 kg"
2,"Job elements list - 15,87MM ATA 12000 SC 16/01...",4086,1,02:50:56,"15,80 mm","14,26 %","1.123,71 kg"
3,"Job elements list - 15,87MM ATA 12000 SC 16/01...",4086,1,02:50:56,"15,80 mm","14,26 %","1.123,71 kg"
4,"Job elements list - 15,87MM ATA 12000 SC 16/01...",4086,1,02:50:56,"15,80 mm","14,26 %","1.123,71 kg"

In [22]:
def convert_str_to_float(dataframe,coluna):
    lista_numeric = []
    lista = dataframe[coluna].values.tolist()
    for item in lista:
        item = item.replace('.','')
        item = item.replace(',','.')
        item = item.replace(' kg','')
        item = item.replace(' %','')
        lista_numeric.append(float(item))
    dataframe[coluna] = lista_numeric

In [9]:
dados['Nome_Programa'] = dados['Nome_Programa'].str.replace('Job elements list - ','',regex=True)

C:\Users\renan\AppData\Local\Temp\ipykernel_1580\1344623376.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados['Nome_Programa'] = dados['Nome_Programa'].str.replace('Job elements list - ','',regex=True)

In [10]:
texto = dados['Nome_Programa'].values[0]
texto

'09,52MM GRADE 08/12 - 15/12'

In [11]:
print(texto.find('MM'))

5

In [12]:
def cria_nome_programa(dataframe, coluna):
    nomes = []
    for item in dataframe[coluna]:
        nomes.append(item[item.find('MM')+3:])
    dataframe[coluna] = nomes

In [27]:
dados.head()

,1,7,19,25,28,31,40
0,"Job elements list - 15,87MM ATA 12000 SC 16/01...",4086,1,02:50:56,"15,80 mm","14,26 %","1.123,71 kg"
1,"Job elements list - 15,87MM ATA 12000 SC 16/01...",4086,1,02:50:56,"15,80 mm","14,26 %","1.123,71 kg"
2,"Job elements list - 15,87MM ATA 12000 SC 16/01...",4086,1,02:50:56,"15,80 mm","14,26 %","1.123,71 kg"
3,"Job elements list - 15,87MM ATA 12000 SC 16/01...",4086,1,02:50:56,"15,80 mm","14,26 %","1.123,71 kg"
4,"Job elements list - 15,87MM ATA 12000 SC 16/01...",4086,1,02:50:56,"15,80 mm","14,26 %","1.123,71 kg"

In [30]:
convert_str_to_float(dados,40)
convert_str_to_float(dados,31)
#cria_nome_programa(dados,40)

C:\Users\renan\AppData\Local\Temp\ipykernel_9560\1495621030.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe[coluna] = lista_numeric

AttributeError: 'float' object has no attribute 'replace'

In [31]:
dados.head()

,1,7,19,25,28,31,40
0,"Job elements list - 15,87MM ATA 12000 SC 16/01...",4086,1,02:50:56,"15,80 mm",14.26,1123.71
1,"Job elements list - 15,87MM ATA 12000 SC 16/01...",4086,1,02:50:56,"15,80 mm",14.26,1123.71
2,"Job elements list - 15,87MM ATA 12000 SC 16/01...",4086,1,02:50:56,"15,80 mm",14.26,1123.71
3,"Job elements list - 15,87MM ATA 12000 SC 16/01...",4086,1,02:50:56,"15,80 mm",14.26,1123.71
4,"Job elements list - 15,87MM ATA 12000 SC 16/01...",4086,1,02:50:56,"15,80 mm",14.26,1123.71

In [32]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1       45 non-null     object
 1   7       45 non-null     int64
 2   19      45 non-null     int64
 3   25      45 non-null     object
 4   28      45 non-null     object
 5   31      45 non-null     float64
 6   40      45 non-null     float64
dtypes: float64(2), int64(2), object(3)
memory usage: 2.6+ KB

In [16]:
def converter_tempo(texto):
    try:
        ponto = texto.find(":")
        hora = int(texto[:ponto])
        minuto = int(texto[ponto+1:])
        tempo =hora + round(minuto/60,2)

        return tempo
    except:
        return 00.00

In [17]:
tempo = dados.Tempo_corte.values[0]
tempo[0:5]

'03:22'

In [18]:
converter_tempo(tempo[0:5])

3.37

In [27]:
dados.head(11)

          Nome_Programa   CNC  Qtd Tempo_corte Espessura  Desperdicio    Peso
0   GRADE 08/12 - 15/12  3807    2    03:22:41   9,52 mm         8.21  681.56
1   GRADE 08/12 - 15/12  3807    2    03:22:41   9,52 mm         8.21  681.56
2   GRADE 08/12 - 15/12  3807    2    03:22:41   9,52 mm         8.21  681.56
3   GRADE 08/12 - 15/12  3807    2    03:22:41   9,52 mm         8.21  681.56
4   GRADE 08/12 - 15/12  3807    2    03:22:41   9,52 mm         8.21  681.56
5   GRADE 08/12 - 15/12  3807    2    03:22:41   9,52 mm         8.21  681.56
6   GRADE 08/12 - 15/12  3807    2    03:22:41   9,52 mm         8.21  681.56
7   GRADE 08/12 - 15/12  3807    2    03:22:41   9,52 mm         8.21  681.56
8   GRADE 08/12 - 15/12  3807    2    03:22:41   9,52 mm         8.21  681.56
9   GRADE 08/12 - 15/12  3807    2    03:22:41   9,52 mm         8.21  681.56
10  GRADE 08/12 - 15/12  3808    1    00:40:14   9,52 mm         6.32  677.07

In [21]:
dados[['Tempo_corte','Qtd']].values[0][0]

'03:22:41'

In [29]:
lista = []
for item in dados.Tempo_corte:
    lista.append(round(converter_tempo(item[0:5]),2))

print(lista)
dados['tempo_decimal'] = lista

[3.37, 3.37, 3.37, 3.37, 3.37, 3.37, 3.37, 3.37, 3.37, 3.37, 0.67, 0.67, 0.67, 0.67, 0.67, 0.67, 1.68, 1.68, 1.68, 1.68, 1.68, 1.88, 1.88, 1.88, 1.88, 3.1, 3.1, 3.1, 3.1, 3.1, 1.48, 1.48, 1.48, 1.48, 1.48, 1.48, 1.48, 1.48, 1.48, 1.48, 1.48, 1.48, 1.48, 1.48, 1.48, 1.48, 1.48, 1.48, 1.48, 1.48, 1.48, 1.48, 1.48, 0.62, 0.62, 0.62, 0.62, 0.62, 0.62, 0.62, 0.62, 0.62, 0.62, 0.62, 0.62, 0.62, 0.62, 0.02, 0.07]

In [23]:
len(lista)

69

In [22]:
lista = []
for itens in dados[['Tempo_corte','Qtd']].values:
    lista.append(converter_tempo(itens[0][0:5])/itens[1])
    
print(lista)

[1.685, 1.685, 1.685, 1.685, 1.685, 1.685, 1.685, 1.685, 1.685, 1.685, 0.67, 0.67, 0.67, 0.67, 0.67, 0.67, 0.8400000000000001, 0.8400000000000001, 0.8400000000000001, 0.8400000000000001, 0.8400000000000001, 0.94, 0.94, 0.94, 0.94, 3.1, 3.1, 3.1, 3.1, 3.1, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.62, 0.62, 0.62, 0.62, 0.62, 0.62, 0.62, 0.62, 0.62, 0.62, 0.62, 0.62, 0.62, 0.62, 0.02, 0.023333333333333334]

In [32]:
dados.head()

,Nome_Programa,CNC,Qtd,Tempo_corte,Espessura,Desperdicio,Peso,tempo_decimal
0,ATA 12000 SC 28/11/2022,3628,1,00:36:36,"9,52 mm",32.02,338.54,0.6
1,ATA 12000 SC 28/11/2022,3628,1,00:36:36,"9,52 mm",32.02,338.54,0.6
2,ATA 12000 SC 28/11/2022,3628,1,00:36:36,"9,52 mm",32.02,338.54,0.6
3,ATA 12000 SC 28/11/2022,3628,1,00:36:36,"9,52 mm",32.02,338.54,0.6
4,ATA 12000 SC 28/11/2022,3628,1,00:36:36,"9,52 mm",32.02,338.54,0.6

In [46]:
today = date.today()

In [47]:
today

datetime.date(2023, 1, 16)

In [48]:
dados['maquina'] = 'LASER-1'
dados['inicio'] = date.today()
dados['tipo'] = 'Transbordo'
dados['status'] = 'Programado'
dados['retalho'] = 0

In [49]:
dados.head()

,Nome_Programa,Espessura,maquina,inicio,Peso,Desperdicio,retalho,CNC,tempo_decimal,tipo,status
0,ATA 12000 SC 28/11/2022,"9,52 mm",LASER-1,2023-01-16,338.54,32.02,0,3628,0.6,Transbordo,Programado
1,ATA 12000 SC 28/11/2022,"9,52 mm",LASER-1,2023-01-16,338.54,32.02,0,3628,0.6,Transbordo,Programado
2,ATA 12000 SC 28/11/2022,"9,52 mm",LASER-1,2023-01-16,338.54,32.02,0,3628,0.6,Transbordo,Programado
3,ATA 12000 SC 28/11/2022,"9,52 mm",LASER-1,2023-01-16,338.54,32.02,0,3628,0.6,Transbordo,Programado
4,ATA 12000 SC 28/11/2022,"9,52 mm",LASER-1,2023-01-16,338.54,32.02,0,3628,0.6,Transbordo,Programado

In [54]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Nome_Programa  10 non-null     object
 1   Espessura      10 non-null     object
 2   maquina        10 non-null     object
 3   inicio         10 non-null     datetime64[ns]
 4   Peso           10 non-null     float64
 5   Desperdicio    10 non-null     float64
 6   retalho        10 non-null     int64
 7   CNC            10 non-null     int64
 8   tempo_decimal  10 non-null     float64
 9   tipo           10 non-null     object
 10  status         10 non-null     object
dtypes: datetime64[ns](1), float64(3), int64(2), object(5)
memory usage: 1008.0+ bytes

In [39]:
dados = dados[['Nome_Programa','Espessura','maquina','inicio','Peso','Desperdicio','retalho','CNC','tempo_decimal','tipo','status']]

In [107]:
def conectarBD():  # Se conecta no servidor
    conexao = psy.connect(
        host="postgres.ata",
        database="pedidos",
        port=5000,
        user="renan",
        password="rev@123"
    )
    return conexao
    
def gera_cursor(conexao: psy):  # retorna o cursor
    cursor = conexao.cursor()
    return cursor

In [42]:
def insert_bd(dataset: pd.DataFrame):
    sql = "INSERT INTO plan_laser(programa, espessura, maquina, inicio, Peso, aproveitamento, retalho, num_nesting, tempo, Tipo, status) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s);"

    for item in dataset.values.tolist():
        cnx = conectarBD()
        cursor = gera_cursor(cnx)
        cursor.execute(sql, item)
        print(cursor.rowcount)
        cnx.commit()

In [55]:
#insert_bd(dados)

1
1
1
1
1
1
1
1
1
1

In [33]:
#dados.to_csv('//192.168.0.171/Informatica/  Renan/2023/laser/Lista_formatada.csv',index=False,sep=';',encoding='utf-8-sig')

# Acertando Banco

In [98]:
correcao_df = pd.read_csv('//192.168.0.171/Informatica/  Renan/2023/laser/acerto.csv',sep=';',encoding='utf8')

In [99]:
correcao_df.head()

   Num Nesting Tempo_uni
0        3.867     0,48
1        3.869     0,11
2        3.868     0,18
3        3.872     0,04
4        3.873     0,07

In [111]:

for itens in correcao_df[['Num Nesting','Tempo_uni']].values:
    cnx = conectarBD()
    cursor = gera_cursor(cnx)
    tempo = itens[1].replace(',','.')
    cnc = str(itens[0]).replace('.','')
    sql = ('Update plan_laser set tempo = {} where num_nesting = {}'.format(tempo,cnc))
    cursor.execute(sql)
    cnx.commit()
    print(sql)

Update plan_laser set tempo =  0.48  where num_nesting = 3867
Update plan_laser set tempo =  0.11  where num_nesting = 3869
Update plan_laser set tempo =  0.18  where num_nesting = 3868
Update plan_laser set tempo =  0.04  where num_nesting = 3872
Update plan_laser set tempo =  0.07  where num_nesting = 3873
Update plan_laser set tempo =  0.05  where num_nesting = 3874
Update plan_laser set tempo =  0.05  where num_nesting = 3876
Update plan_laser set tempo =  0.07  where num_nesting = 3877
Update plan_laser set tempo =  0.09  where num_nesting = 3878
Update plan_laser set tempo =  0.03  where num_nesting = 3882
Update plan_laser set tempo =  0.11  where num_nesting = 3883
Update plan_laser set tempo =  0.07  where num_nesting = 3794
Update plan_laser set tempo =  0.12  where num_nesting = 3795
Update plan_laser set tempo =  0.15  where num_nesting = 3796
Update plan_laser set tempo =  0.29  where num_nesting = 3797
Update plan_laser set tempo =  0.13  where num_nesting = 3798
Update plan_laser set tempo =  0.13  where num_nesting = 3785
Update plan_laser set tempo =  0.14  where num_nesting = 3786
Update plan_laser set tempo =  0.05  where num_nesting = 3787
Update plan_laser set tempo =  0.12  where num_nesting = 3788
Update plan_laser set tempo =  0.16  where num_nesting = 3789
Update plan_laser set tempo =  0.21  where num_nesting = 379
Update plan_laser set tempo =  0.04  where num_nesting = 3791
Update plan_laser set tempo =  0.06  where num_nesting = 3806
Update plan_laser set tempo =  0.17  where num_nesting = 3812
Update plan_laser set tempo =  0.04  where num_nesting = 3818
Update plan_laser set tempo =  0.02  where num_nesting = 3835
Update plan_laser set tempo =  0.09  where num_nesting = 3836
Update plan_laser set tempo =  0.05  where num_nesting = 3837
Update plan_laser set tempo =  0.06  where num_nesting = 3838
Update plan_laser set tempo =  0.18  where num_nesting = 3799
Update plan_laser set tempo =  0.66  where num_nesting = 38
Update plan_laser set tempo =  0.25  where num_nesting = 3801
Update plan_laser set tempo =  0.37  where num_nesting = 3803
Update plan_laser set tempo =  0.12  where num_nesting = 3802